CC=javac
default: Task.class SafeQueue.class Slave.class Master.class Main.class

Task.class: Task.java 
	$(CC) Task.java

SafeQueue.class: SafeQueue.java
	$(CC) SafeQueue.java

Slave.class: Slave.java
	$(CC) Slave.java

Master.class: Master.java
	$(CC) Master.java

Main.class: Main.java
	$(CC) Main.java

clean:
	$(RM) *.class

